
import React from "react";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

const PrivacyPolicy = () => {
  return (
    <div className="flex flex-col min-h-screen">
      <Navbar />
      <main className="flex-grow">
        <div className="container-custom py-12 max-w-4xl mx-auto">
          <h1 className="text-3xl md:text-4xl font-bookmania mb-8 text-center">Privacy Policy</h1>
          
          <div className="bg-white/50 shadow-sm rounded-lg p-6 md:p-8">
            <h2 className="text-xl font-bold mb-4 text-center">NOTICE OF PRIVACY PRACTICES</h2>
            <p className="text-sm text-center mb-4 font-semibold">
              THIS NOTICE DESCRIBES HOW HEALTH INFORMATION MAY BE USED AND DISCLOSED AND HOW
              YOU CAN GET ACCESS TO THIS INFORMATION. PLEASE REVIEW IT CAREFULLY.
            </p>
            
            <section className="mb-6">
              <h3 className="text-lg font-semibold mb-2">I. MY PLEDGE REGARDING HEALTH INFORMATION:</h3>
              <p className="mb-4">
                I understand that health information about you and your health care is personal. I am committed to protecting health
                information about you. I create a record of the care and services you receive from me. I need this record to provide
                you with quality care and to comply with certain legal requirements. This notice applies to all of the records of your
                care generated by this mental health care practice. This notice will tell you about the ways in which I may use and
                disclose health information about you. I also describe your rights to the health information I keep about you, and
                describe certain obligations I have regarding the use and disclosure of your health information. I am required by law
                to:
              </p>
              <ul className="list-disc pl-6 mb-4 space-y-2">
                <li>Make sure that protected health information ("PHI") that identifies you is kept private.</li>
                <li>Give you this notice of my legal duties and privacy practices with respect to health information.</li>
                <li>Follow the terms of the notice that is currently in effect.</li>
                <li>I can change the terms of this Notice, and such changes will apply to all information I have about you.
                  The new Notice will be available upon request.</li>
              </ul>
            </section>
            
            <section className="mb-6">
              <h3 className="text-lg font-semibold mb-2">II. HOW I MAY USE AND DISCLOSE HEALTH INFORMATION ABOUT YOU:</h3>
              <p className="mb-2">The following categories describe different ways that I use and disclose health information.</p>
              
              <h4 className="font-medium mt-4 mb-2">For Treatment Payment, or Health Care Operations:</h4>
              <p className="mb-4">
                Federal privacy rules (regulations) allow health care providers who have direct treatment relationship with the patient/client to use or disclose the patient/client's
                personal health information without the patient's written authorization, to carry out the health care provider's own
                treatment, payment or health care operations. I may also disclose your protected health information for the treatment
                activities of any health care provider. This too can be done without your written authorization. For example, if a
                clinician were to consult with another licensed health care provider about your condition, we would be permitted to
                use and disclose your personal health information, which is otherwise confidential, in order to assist the clinician in
                diagnosis and treatment of your mental health condition.
              </p>
              <p className="mb-4">
                Disclosures for treatment purposes are not limited to the minimum necessary standard. Because therapists and other
                health care providers need access to the full record and/or full and complete information in order to provide quality
                care. The word "treatment" includes, among other things, the coordination and management of health care providers
                with a third party, consultations between health care providers and referrals of a patient for health care from one
                health care provider to another.
              </p>
              
              <h4 className="font-medium mt-4 mb-2">Lawsuits and Disputes:</h4>
              <p className="mb-4">
                If you are involved in a lawsuit, I may disclose health information in response to a court or
                administrative order. I may also disclose health information about your child in response to a subpoena, discovery
                request, or other lawful process by someone else involved in the dispute, but only if efforts have been made to tell
                you about the request or to obtain an order protecting the information requested.
              </p>
            </section>
            
            <section className="mb-6">
              <h3 className="text-lg font-semibold mb-2">III. CERTAIN USES AND DISCLOSURES REQUIRE YOUR AUTHORIZATION:</h3>
              <div className="flex items-center mb-2">
                <p className="text-sm text-emerald-green">The Gift of Peace Counseling & Wellness, PLLC</p>
              </div>
              <div className="flex items-center mb-2">
                <p className="text-sm">P: (980)216-6978</p>
              </div>
              <div className="flex items-center mb-4">
                <p className="text-sm">E: admin@thegiftofpeace.org</p>
              </div>
              
              <ol className="list-decimal pl-6 mb-4 space-y-4">
                <li>
                  <p className="font-medium">Psychotherapy Notes.</p>
                  <p className="mb-2">I do keep "psychotherapy notes" as that term is defined in 45 CFR § 164.501,
                  and any use or disclosure of such notes requires your Authorization unless the use or disclosure is:</p>
                  <ol className="list-[lower-alpha] pl-6 space-y-1">
                    <li>For my use in treating you.</li>
                    <li>For my use in training or supervising mental health practitioners to help them improve their skills
                    in group, joint, family, or individual counseling or therapy.</li>
                    <li>For my use in defending myself in legal proceedings instituted by you.</li>
                    <li>For use by the Secretary of Health and Human Services to investigate my compliance with HIPAA.</li>
                    <li>Required by law and the use or disclosure is limited to the requirements of such law.</li>
                    <li>Required by law for certain health oversight activities pertaining to the originator of the
                    psychotherapy notes.</li>
                    <li>Required by a coroner who is performing duties authorized by law.</li>
                    <li>Required to help avert a serious threat to the health and safety of others.</li>
                  </ol>
                </li>
                <li>
                  <p className="font-medium">Marketing Purposes.</p>
                  <p>As a psychotherapist, I will not use or disclose your PHI for marketing purposes.</p>
                </li>
                <li>
                  <p className="font-medium">Sale of PHI.</p>
                  <p>As a psychotherapist, I will not sell your PHI in the regular course of my business.</p>
                </li>
              </ol>
            </section>
            
            <section className="mb-6">
              <h3 className="text-lg font-semibold mb-2">IV. CERTAIN USES AND DISCLOSURES DO NOT REQUIRE YOUR AUTHORIZATION.</h3>
              <p className="mb-4">
                Subject to certain limitations in the law, I can use and disclose your PHI without your Authorization for the
                following reasons:
              </p>
              <ol className="list-decimal pl-6 mb-4 space-y-2">
                <li>When disclosure is required by state or federal law, and the use or disclosure complies with and is
                limited to the relevant requirements of such law.</li>
                <li>For public health activities, including reporting suspected child, elder, or dependent adult abuse, or
                preventing or reducing a serious threat to anyone's health or safety.</li>
                <li>For health oversight activities, including audits and investigations.</li>
                <li>For judicial and administrative proceedings, including responding to a court or administrative order,
                although my preference is to obtain an Authorization from you before doing so.</li>
                <li>For law enforcement purposes, including reporting crimes occurring on my premises.</li>
                <li>To coroners or medical examiners, when such individuals are performing duties authorized by law.</li>
                <li>For research purposes, including studying and comparing the mental health of patients who received
                one form of therapy versus those who received another form of therapy for the same condition.</li>
                <li>Specialized government functions, including, ensuring the proper execution of military missions;
                protecting the President of the United States; conducting intelligence or counter-intelligence
                operations; or, helping to ensure the safety of those working within or housed in correctional
                institutions.</li>
                <li>For workers' compensation purposes. Although my preference is to obtain an Authorization from
                you, I may provide your PHI in order to comply with workers' compensation laws.</li>
                <li>Appointment reminders and health related benefits or services. I may use and disclose your PHI to
                contact you to remind you that you have an appointment with me. I may also use and disclose your
                PHI to tell you about treatment alternatives, or other health care services or benefits that I offer.</li>
              </ol>
            </section>
            
            <section className="mb-6">
              <h3 className="text-lg font-semibold mb-2">V. CERTAIN USES AND DISCLOSURES REQUIRE YOU TO HAVE THE OPPORTUNITY TO OBJECT.</h3>
              <div className="flex items-center mb-2">
                <p className="text-sm text-emerald-green">The Gift of Peace Counseling & Wellness, PLLC</p>
              </div>
              <div className="flex items-center mb-2">
                <p className="text-sm">P: (980)216-6978</p>
              </div>
              <div className="flex items-center mb-4">
                <p className="text-sm">E: admin@thegiftofpeace.org</p>
              </div>
              
              <ol className="list-decimal pl-6 mb-4">
                <li>
                  <p className="font-medium">Disclosures to family, friends, or others.</p>
                  <p>I may provide your PHI to a family member, friend, or other
                  person that you indicate is involved in your care or the payment for your health care, unless you
                  object in whole or in part. The opportunity to consent may be obtained retroactively in emergency
                  situations.</p>
                </li>
              </ol>
            </section>
            
            <section className="mb-6">
              <h3 className="text-lg font-semibold mb-2">VI. YOU HAVE THE FOLLOWING RIGHTS WITH RESPECT TO YOUR PHI:</h3>
              <ol className="list-decimal pl-6 mb-4 space-y-2">
                <li>The Right to Request Limits on Uses and Disclosures of Your PHI. I am not required to agree to your
                request, and I may say "no" if I believed it would affect your health care.</li>
                <li>The Right to Request Restrictions for Out-of-Pocket Expenses Paid for In Full. You have the right to
                request restrictions on disclosures of your PHI to health plans for payment or health care operations
                purposes if the PHI pertains solely to a health care item or a health care service that you have paid for
                out-of-pocket in full.</li>
                <li>The Right to Choose How I Send PHI to You. You have the right to ask me to contact you in a
                specific way (for example, home or office phone) or to send mail to a different address, and I will
                agree to all reasonable requests.</li>
                <li>The Right to See and Get Copies of Your PHI. Other than "psychotherapy notes," you have the right
                to get an electronic or paper copy of your medical record and other information that I have about you.
                I will provide you with a copy of your record, or a summary of it, if you agree to receive a summary,
                within 30 days of receiving your written request, and I may charge a reasonable, cost based fee for
                doing so.</li>
                <li>The Right to Get a List of the Disclosures I Have Made. You have the right to request a list of
                instances in which I have disclosed your PHI for purposes other than treatment, payment, or health
                care operations, or for which you provided me with an Authorization.</li>
                <li>The Right to Correct or Update Your PHI. If you believe that there is a mistake in your PHI, or that a
                piece of important information is missing from your PHI, you have the right to request that I correct
                the existing information or add the missing information. I may say "no" to your request, but I will tell
                you why in writing within 60 days of receiving your request.</li>
                <li>The Right to Get a Paper or Electronic Copy of this Notice. You have the right get a paper copy of
                this Notice, and you have the right to get a copy of this notice by e-mail. And, even if you have
                agreed to receive this Notice via e-mail, you also have the right to request a paper copy of it.</li>
              </ol>
            </section>
            
            <section>
              <h3 className="text-lg font-semibold mb-2">COMPLAINTS</h3>
              <p>
                If you believe I have violated your privacy rights, you have the right to file a complaint in writing with the Secretary
                of Health and Human Services at 3724 National Drive, Suite 100 Raleigh, NC 27612 or by calling (919) 856-2195
                or Customer Services and Community Rights by calling 919- 715-3197 or Toll Free: 1-855-262-1946. I will not
                retaliate against you for filing a complaint.
              </p>
            </section>
          </div>
        </div>
      </main>
      <Footer />
    </div>
  );
};

export default PrivacyPolicy;
