// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rnlwovbygyomxzjzbqgv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJubHdvdmJ5Z3lvbXh6anpicWd2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ2NzQ1MzcsImV4cCI6MjA2MDI1MDUzN30.-d-ZM2svULiUPAOV1oYXDSTakqsCrn00E8za4nc7IQ4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);